export namespace Novax {
  /**
   * This file was auto-generated by openapi-typescript.
   * Do not make direct changes to the file.
   */

  export interface definitions {
    TypeEnum: { label: string; value: never };
    Options: { id: number; name: string };

    OptionsDropdown: {
      id: number;
      name: string;
      inactive: boolean;
    };

    OptionString: {
      label: string;
      value: string;
    };

    OptionBoolean: {
      label: string;
      value: boolean;
    };

    /** ConfigEmailInput */
    ConfigEmailInput: {
      emailBody?: string;
    };

    /** ConfigEmailModel */
    ConfigEmailModel: {
      emailBody?: string;
    };

    ConfigVoucherInput: {
      emailBody?: string;
      senderMail?: boolean;
      daysToCancel?: number;
      daysToExpire?: number;
      numberPendingVouchers?: number;
    };

    /** ConfigVoucherModel */
    ConfigVoucherModel: {
      emailBody?: string;
      senderMail?: boolean;
      daysToCancel?: number;
      daysToExpire?: number;
      numberPendingVouchers?: number;
    };

    /** FleetsModel */
    FleetsModel: {
      id: number;

      createdBy: definitions['UserMinimalModel'];
    };

    /** FleetsInput */
    FleetsInput: {
      name: string;

      initialValidate?: Date;
    };

    /** ProductModel */
    ProductModel: {
      id: number;
      name: string;
      status: string;
      amount: number;
      typeProduct: string;
      description: string;
      finalValidate: Date;
      initialValidate: Date;
      createdBy: definitions['UserMinimalModel'];
    };

    /** ProductMinimalModel */
    ProductMinimalModel: {
      id: number;
      name: string;
      amount: number;
    };

    /** ProductInput */
    ProductInput: {
      name: string;
      status?: string;
      amount?: number;
      typeProduct?: string;
      description?: string;
      finalValidate?: Date;
      initialValidate?: Date;
    };

    /** EmployeeModel */
    EmployeeModel: {
      id: number;
      name: string;
      code: number;
      statusEmployee: string;
      isManager: boolean;
      isAttendant: boolean;
    };

    /** EmployeeInput */
    EmployeeInput: {
      name: string;
    };

    /** TourGuideModel */
    TourGuideModel: {
      id: number;
      name: string;
      code: number;
      statusTourGuide: string;
      isManager: boolean;
      isAttendant: boolean;
    };

    /** TourGuideInput */
    TourGuideInput: {
      name: string;
    };

    /** ChangePasswordUserInput */
    ChangePasswordUserInput: {
      id: number;
      password: string;
      oldPassword: string;
    };

    /** PromoterModel */
    PromoterModel: {
      id: number;
      code: number;
      name: string;
      statusPromoter: string;
    };

    /** PromoterInput */
    PromoterInput: {
      name: string;
    };

    /** GroupModel */
    GroupModel: {
      id: number;
      name: string;
      description: string;
    };

    /** GroupInput */
    GroupInput: {
      name: string;
      description: string;
    };

    /** MaintenanceInput */
    MaintenanceInput: {
      note: string;
      description: string;
      sendDate: Date;
      returnDate: Date;
      warrantyEnd: Date;
      warrantyStart: Date;
      price: number;
      status: string;
      typeMaintenance: string;
      equipment: definitions['IdInput'];
      authorized: definitions['IdInput'];
    };

    /** MaintenanceModel */
    MaintenanceModel: {
      uuid: string;
      note: string;
      status: string;
      description: string;
      typeMaintenance: string;
      sendDate: Date;
      returnDate: Date;
      warrantyEnd: Date;
      warrantyStart: Date;
      price: number;

      authorized: definitions['AgentMinimalModel'];
      equipment: definitions['EquipmentSummaryModel'];
    };

    /** MaintenanceScheduleModel */
    MaintenanceScheduleModel: {
      uuid: string;
      note: string;
      status: string;
      frequency: string;
      typeMaintenance: string;
      notificationProfile: string;
      nextMaintenance: Date;
      equipment: definitions['EquipmentSummaryModel'];
    };

    /** MaintenanceScheduleInput */
    MaintenanceScheduleInput: {
      note: string;
      status: string;
      frequency: string;
      typeMaintenance: string;
      notificationProfile: string;
      equipment: definitions['IdInput'];
    };

    /** AgentInput */
    AgentInput: {
      name: string;
      document: string;
      typePerson: string;
      rg: string;
      sex: string;
      isManager: boolean;
      isAttendant: boolean;
      civilState: string;
      statusClient: string;
      birthDate: Date;
      socialReason: string;
      statusProvider: string;
      statusPromoter: string;
      statusEmployee: string;
      statusTourGuide: string;
    };

    /** AgentModel */
    AgentModel: {
      id: number;
      rg: string;
      sex: string;
      name: string;
      code: number;
      isManager: boolean;
      isAttendant: boolean;
      document: string;
      typePerson: string;
      civilState: string;
      statusClient: string;
      socialReason: string;
      birthDate: Date;
      statusProvider: string;
      statusEmployee: string;
      statusPromoter: string;
      statusTourGuide: string;

      address: definitions['AddressModel'][];
      contacts: definitions['ContactModel'][];
      agentTypes?: definitions['AgentTypeMinimalModel'];
    };

    /** AgentMinimalModel */
    AgentMinimalModel: {
      name: string;
      code: number;
      id: number;
    };

    /** AgentSummaryModel */
    AgentSummaryModel: {
      id: number;
      name: string;
      code: number;
      document: string;
    };

    /** AgentTypeMinimalModel */
    AgentTypeMinimalModel: {
      id: number;
      agentType: string;
    };

    /** AgentTypeInput */
    AgentTypeInput: {
      agentType: string;
    };

    /** AddressModel */
    AddressModel: {
      id: number;
      burgh: string;
      street: string;
      number: string;
      postalCode: string;
      complement: string;
      city: definitions['CityModel'];
    };

    /** AddressInput */
    AddressInput: {
      burgh: string;
      street: string;
      number: string;
      complement: string;
      postalCode: string;
      city: definitions['IdInput'];
      agent: definitions['IdInput'];
    };

    /** ContactModel */
    ContactModel: {
      id: number;
      name: string;
      email: string;
      cellphone: string;
      telephone: string;
    };

    /** CityModel */
    CityModel: {
      id: number;
      name: string;
      state: definitions['StateModel'];
    };

    /** CityInput */
    CityInput: {
      name: string;
      state: definitions['IdInput'];
    };

    /** StateInput */
    StateInput: {
      uf: string;
      name: string;
    };

    /** StateModel */
    StateModel: {
      id: number;
      uf: string;
      name: string;
    };

    /** CancellationReasonModel */
    CancellationReasonModel: {
      id: number;
      name: string;
      status: string;
      generation: string;
      description: string;
      createdAt: Date;
    };

    /** CancellationReasonInput */
    CancellationReasonInput: {
      name: string;
      description: string;
      status: string;
    };

    /** PoolParametersModel */
    PoolParametersModel: {
      uuid: string;
      note: string;
      ph: string;
      pool: string;
      shift: string;
      chlorine: string;
      alkalinity: string;
      createdAt: Date;
      employee: definitions['AgentMinimalModel'];
    };

    /** PoolParametersInput */
    PoolParametersInput: {
      note: string;
      ph: string;
      pool: string;
      shift: string;
      chlorine: string;
      alkalinity: string;
      employee: definitions['IdInput'];
    };

    /** EquipmentModel */
    EquipmentModel: {
      uuid: string;
      note: string;
      status: string;
      voltage: string;
      description: string;
      patrimonyNumber: number;
      buyDate: Date;
      arrivalDate: Date;
      warrantyEnd: Date;
      warrantyStart: Date;
      price: number;
      totalMaintenance: number;
      provider: definitions['AgentMinimalModel'];
      historical: definitions['HistoricMinimalModel'][];
      maintenances: definitions['MaintenanceSummaryModel'][];
    };

    /** EquipmentSummaryModel */
    EquipmentSummaryModel: {
      id: number;
      price: number;
      description: string;
      patrimonyNumber: number;
      buyDate: Date | undefined;
      arrivalDate: Date | undefined;
      maintenances: definitions['MaintenanceSummaryModel'][];
    };

    /** EquipmentInput */
    EquipmentInput: {
      uuid: string;
      note: string;
      status: string;
      voltage: string;
      description: string;
      patrimonyNumber: number;
      buyDate: Date;
      arrivalDate: Date;
      warrantyEnd: Date;
      warrantyStart: Date;
      price: number;
      totalMaintenance: number;
      provider: definitions['AgentMinimalModel'];
      historical: definitions['HistoricMinimalModel'][];
      maintenances: definitions['MaintenanceSummaryModel'][];
    };

    /** LocationModel */
    LocationModel: {
      id: number;
      uuid: string;
      note: string;
      status: string;
      generation: string;
      description: string;
      createdAt: Date;
      createdBy: definitions['UserMinimalModel'];
    };

    /** LocationInput */
    LocationInput: {
      id: number;
      uuid: string;
      status: string;
      description: string;
    };

    /** HistoricModel */
    HistoricModel: {
      note: string;
      uuid: string;
      status: string;
      generation: string;
      finalDate: Date;
      initialDate: Date;
      location: definitions['LocationMinimalModel'];
      equipment: definitions['EquipmentSummaryModel'];
    };

    /** HistoricMinimalModel */
    HistoricMinimalModel: {
      uuid: string;
      status: string;
      description: string;
      finalDate: Date;
      initialDate: Date;

      location: definitions['LocationMinimalModel'];
    };

    /** HistoricInput */
    HistoricInput: {
      note: string;
      finalDate: Date;
      initialDate: Date;
      status: string;
      location: definitions['IdInput'];
      equipment: definitions['IdInput'];
    };

    /** MaintenanceSummaryModel */
    MaintenanceSummaryModel: {
      uuid: string;
      status: string;
      description: string;
      sendDate: Date;
      returnDate: Date;
      warrantyEnd: Date;
      price: number;
      authorized: definitions['AgentMinimalModel'];
    };

    /** LocationMinimalModel */
    LocationMinimalModel: {
      id: number;
      uuid: string;
      description: string;
    };

    /** ProviderModel */
    ProviderModel: {
      id: number;
      name: string;
      code: number;
      statusProvider: string;
    };

    /** ProviderInput */
    ProviderInput: {
      client: string;
    };

    /** CourtesyModel */
    CourtesyModel: {
      uuid: string;
      status: string;
      client: string;
      document: string;
      actualVisitDate: Date;
      scheduledVisitDate: Date;
      removedBy: definitions['AgentMinimalModel'];
      authorizedBy: definitions['AgentMinimalModel'];
    };

    /** CourtesyInput */
    CourtesyInput: {};

    CourtesyReplacementInput: {
      courtesyIds: string[];
      actualVisitDate: Date;
      removedBy: definitions['IdInput'];
    };

    /** VoucherModel */
    VoucherModel: {
      id: number;
      uuid: string;
      note: string;
      status: string;
      voucher: string;
      typePerson: string;
      cancellationReason: string;

      visitDate: Date;
      totalPrice: number;
      advanceValue: number;

      client: definitions['AgentSummaryModel'];
      promoter: definitions['AgentMinimalModel'];
      tourGuide: definitions['AgentMinimalModel'];

      foods: definitions['FoodInput'][];
      tickets: definitions['TicketInput'][];
    };

    /** VoucherInput */
    VoucherInput: {
      note: string;
      voucher: string;
      status: string;
      typePerson: string;
      visitDate: Date;
      advanceValue: number;
      client: definitions['IdInput'];
      promoter: definitions['IdInput'];
      tourGuide: definitions['IdInput'];
      foods: definitions['FoodInput'][];
      tickets: definitions['TicketInput'][];
    };

    /** VoucherCancellationInput */
    VoucherCancellationInput: {
      cancellationReason: definitions['IdInput'];
    };

    /** FoodModel */
    FoodModel: {
      id: number;
      quantity: number;

      unitPrice: number;
      totalPrice: number;

      product: definitions['ProductMinimalModel'];
    };

    /** FoodInput */
    FoodInput: {
      quantity: number;
      unitPrice: number;
      product: definitions['IdInput'];
    };

    /** TicketInput */
    TicketInput: {
      quantity: number;
      unitPrice: number;
      product: definitions['IdInput'];
    };

    /** TicketModel */
    TicketModel: {
      id: number;
      quantity: number;

      unitPrice: number;
      totalPrice: number;

      product: definitions['ProductMinimalModel'];
    };

    /** CostCenterDetailedModel */
    CostCenterDetailedModel: {
      _links?: definitions['Links'];
      canBeDeleted?: boolean;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      createdAt?: Date;
      createdBy?: definitions['UserMinimalModel'];
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example João da Silva */
      name?: string;
      /** Format: int64 */
      totalEntries?: number;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      updatedAt?: Date;
      updatedBy?: definitions['UserMinimalModel'];
    };
    /** CostCenterInput */
    CostCenterInput: {
      description?: string;
    };
    /** CostCenterMinimalModel */
    CostCenterMinimalModel: {
      _links?: definitions['Links'];
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Alimentação */
      description?: string;
    };
    /** CostCenterSummaryModel */
    CostCenterSummaryModel: {
      _links?: definitions['Links'];
      canBeDeleted?: boolean;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Infra */
      description?: string;
      /**
       * Format: int64
       * @example 20
       */
      totalEntries?: number;
    };
    /** ClassMovementInput */
    ClassMovementInput: {
      description?: string;
    };
    /** ClassMovementMinimalModel */
    ClassMovementMinimalModel: {
      _links?: definitions['Links'];
      /** @example João da Silva */
      description?: string;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
    };
    /** ClassMovementSummaryModel */
    ClassMovementSummaryModel: {
      _links?: definitions['Links'];
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      createdAt?: Date;
      createdBy?: definitions['UserMinimalModel'];
      /** @example Itau */
      description?: string;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      updatedAt?: Date;
      updatedBy?: definitions['UserMinimalModel'];
    };
    /** CollectionModel«CostCenterSummaryModel» */
    'CollectionModel«CostCenterSummaryModel»': {
      _embedded?: definitions['CostCenterSummaryModel'][];
      _links?: definitions['Links'];
    };
    /** CollectionModel«DocumentTypeModel» */
    'CollectionModel«DocumentTypeModel»': {
      _embedded?: definitions['DocumentTypeModel'][];
      _links?: definitions['Links'];
    };
    /** CollectionModel«EntryFlowModel» */
    'CollectionModel«EntryFlowModel»': {
      _embedded?: definitions['EntryFlowModel'][];
      _links?: definitions['Links'];
    };
    /** DocumentTypeModel */
    DocumentTypeModel: {
      _links?: definitions['Links'];
      /** @example João da Silva */
      description?: string;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example João da Silva */
      nature?: string;
    };
    /** EntryDetailedModel */
    EntryDetailedModel: {
      _links?: definitions['Links'];
      /** @example 50 */
      amount?: number;
      canBeDeleted?: boolean;
      canBeEdited?: boolean;
      category?: definitions['CostCenterMinimalModel'];
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      createdAt?: Date;
      createdBy?: definitions['UserMinimalModel'];
      /** @example Alimentação */
      description?: string;
      /**
       * Format: date
       * @example 2022-05-02
       */
      dueDate?: Date;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      systemGenerated?: boolean;
      /**
       * Format: date
       * @example 2022-05-02
       */
      transactedOn?: Date;
      /**
       * @example REVENUE
       * @enum {string}
       */
      type?: 'REVENUE' | 'EXPENSE';
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      updatedAt?: Date;
      updatedBy?: definitions['UserMinimalModel'];
    };
    /** EntryFlowModel */
    EntryFlowModel: {
      _links?: definitions['Links'];
      actualBalance?: number;
      amount?: number;
      balance?: number;
      category?: string;
      description?: string;
      /** Format: date */
      dueDate?: Date;
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      idAccount?: number;
      previousBalance?: number;
      /** Format: date */
      transactedOn?: Date;
      /** @enum {string} */
      type?: 'REVENUE' | 'EXPENSE';
    };
    /** EntryInput */
    EntryInput: {
      account: definitions['IdInput'];
      amount: number;
      description?: string;
      /** Format: int32 */
      document?: number;
      /** Format: date */
      dueDate: Date;
      movements: definitions['MovementInput'][];
      /** Format: date */
      transactedOn: Date;
      /** @enum {string} */
      type: 'REVENUE' | 'EXPENSE';
    };
    /** EntryMovementDetailedModel */
    EntryMovementDetailedModel: {
      _links?: definitions['Links'];
      agent?: definitions['AgentMinimalModel'];
      /** @example 50 */
      amount?: number;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      createdAt?: Date;
      createdBy?: definitions['UserMinimalModel'];
      /** @example 123 */
      document?: string;
      documentType?: definitions['DocumentTypeModel'];
      /**
       * Format: date
       * @example 2022-05-02
       */
      dueDate?: Date;
      /** @example Alimentação */
      historic?: string;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      movements?: definitions['MovementDetailedModel'][];
      /**
       * Format: date
       * @example 2022-05-02
       */
      transactedOn?: Date;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      updatedAt?: Date;
      updatedBy?: definitions['UserMinimalModel'];
    };
    /** EntryMovementSummaryModel */
    EntryMovementSummaryModel: {
      _links?: definitions['Links'];
      agent?: definitions['AgentMinimalModel'];
      /** @example 50 */
      amount?: number;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      createdAt?: Date;
      createdBy?: definitions['UserMinimalModel'];
      /** @example 123 */
      document?: string;
      documentType?: definitions['DocumentTypeModel'];
      /**
       * Format: date
       * @example 2022-05-02
       */
      dueDate: Date;
      /** @example Alimentação */
      historic?: string;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      movements?: definitions['MovementDetailedModel'][];
      /**
       * Format: date
       * @example 2022-05-02
       */
      transactedOn: Date;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      updatedAt?: Date;
      updatedBy?: definitions['UserMinimalModel'];
    };
    /** EntryMovementInput */
    EntryMovementInput: {
      agent: definitions['IdInput'];
      amount: number;
      document?: string;
      documentType: definitions['IdInput'];
      /** Format: date */
      dueDate: Date;
      historic?: string;
      movements?: definitions['MovementInput'][];
      /** Format: date */
      transactedOn: Date;
    };
    /** EntrySummaryModel */
    EntrySummaryModel: {
      _links?: definitions['Links'];
      account?: definitions['AgentSummaryModel'];
      /** @example 50 */
      amount?: number;
      canBeDeleted?: boolean;
      canBeEdited?: boolean;
      category?: definitions['CostCenterMinimalModel'];
      /** @example Alimentação */
      description?: string;
      /**
       * Format: date
       * @example 2022-05-02
       */
      dueDate?: Date;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      systemGenerated?: boolean;
      /**
       * Format: date
       * @example 2022-05-02
       */
      transactedOn?: Date;
      /**
       * @example REVENUE
       * @enum {string}
       */
      type?: 'REVENUE' | 'EXPENSE';
    };

    /** GroupsModel */
    GroupsModel: {
      _embedded?: definitions['GruposEmbeddedModel'];
      _links?: definitions['Links'];
    };
    /** GruposEmbeddedModel */
    GruposEmbeddedModel: {
      grupos?: definitions['GroupModel'][];
    };
    /** IdInput */
    IdInput: {
      /**
       * Format: int64
       * @example 1
       */
      id: number;
    };
    /** Link */
    Link: {
      href?: string;
      templated?: boolean;
    };
    /** Links */
    Links: {
      rel?: definitions['Link'];
    };
    /** MovementDetailedModel */
    MovementDetailedModel: {
      _links?: definitions['Links'];
      agent?: definitions['AgentMinimalModel'];
      /** @example 50 */
      amount?: number;
      category?: definitions['CostCenterMinimalModel'];
      classMovement?: definitions['ClassMovementMinimalModel'];
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      createdAt?: Date;
      createdBy?: definitions['UserMinimalModel'];
      /** @example 123 */
      document?: string;
      documentType?: definitions['DocumentTypeModel'];
      /** @example Alimentação */
      historic?: string;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      updatedAt?: Date;
      updatedBy?: definitions['UserMinimalModel'];
    };
    /** MovementInput */
    MovementInput: {
      agent: definitions['IdInput'];
      amount: number;
      category: definitions['IdInput'];
      classMovement: definitions['IdInput'];
      document?: string;
      documentType: definitions['IdInput'];
      historic?: string;
    };
    /** PageMetadata */
    PageMetadata: {
      /** Format: int64 */
      number?: number;
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int64 */
      totalPages?: number;
    };
    /** PagedModel«AgentSummaryModel» */
    'PagedModel«AgentSummaryModel»': {
      _embedded?: definitions['AgentSummaryModel'][];
      _links?: definitions['Links'];
      page?: definitions['PageMetadata'];
    };
    /** PagedModel«ClassMovementSummaryModel» */
    'PagedModel«ClassMovementSummaryModel»': {
      _embedded?: definitions['ClassMovementSummaryModel'][];
      _links?: definitions['Links'];
      page?: definitions['PageMetadata'];
    };
    /** PagedModel«EntrySummaryModel» */
    'PagedModel«EntrySummaryModel»': {
      _embedded?: definitions['EntrySummaryModel'][];
      _links?: definitions['Links'];
      page?: definitions['PageMetadata'];
    };
    /** PagedModel«GroupModel» */
    'PagedModel«GroupModel»': {
      _embedded?: definitions['GroupModel'][];
      _links?: definitions['Links'];
      page?: definitions['PageMetadata'];
    };
    /** PagedModel«UserModel» */
    'PagedModel«UserModel»': {
      _embedded?: definitions['UserModel'][];
      _links?: definitions['Links'];
      page?: definitions['PageMetadata'];
    };
    /** PermissionModel */
    PermissionModel: {
      _embedded?: definitions['PermissoesEmbeddedModel'];
      _links?: definitions['Links'];
      /** @example Permite consultar cozinhas */
      description?: string;
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example CONSULTAR_COZINHAS */
      name: string;
    };
    /** PermissoesEmbeddedModel */
    PermissoesEmbeddedModel: {
      permissions?: definitions['PermissionModel'][];
    };
    /** Problem */
    Problem: {
      /**
       * Format: int32
       * @example 400
       */
      status?: number;
      /**
       * Format: date-time
       * @example 2019-12-01T18:09:02.70844Z
       */
      timestamp?: string;
      /** @example https://ws.com.br/invalid-data */
      type?: string;
      /** @example Dados inválidos */
      title?: string;
      /** @example Um ou mais campos estão inválidos. Faça o preenchimento correto e tente novamente. */
      detail?: string;
      /** @example Um ou mais campos estão inválidos. Faça o preenchimento correto e tente novamente. */
      userMessage?: string;
      /** @description Lista de objetos ou campos que geraram o erro (opcional) */
      objects?: definitions['ProblemObject'][];
    };
    /** ProblemObject */
    ProblemObject: {
      /** @example preco */
      name?: string;
      /** @example O preço é obrigatório */
      userMessage?: string;
    };
    /** UserInput */
    UserInput: {
      active: boolean;
      /** Format: date */
      birthDate: Date;
      /** @example joao.ger@ws.com.br */
      email: string;
      /** @example João da Silva */
      name: string;
    };
    /** UserMinimalModel */
    UserMinimalModel: {
      /**
       * Format: int64
       * @example 1
       */
      id: number;
      /** @example João da Silva */
      name: string;
    };
    /** UserModel */
    UserModel: {
      status: string;
      /**
       * Format: date
       * @example 2022-04-01
       */
      birthDate: Date;
      canBeActivated: boolean;
      canBeDeactivated: boolean;
      /**
       * Format: date-time
       * @example 2022-04-01T13:22:58Z
       */
      createdAt: Date;
      /** @example joao.ger@ws.com.br */
      email: string;
      /**
       * Format: int64
       * @example 1
       */
      id: number;
      /** @example João da Silva */
      name: string;
      document: string;
    };
    /** UsersEmbeddedModel */
    UsersEmbeddedModel: {
      users?: definitions['UserModel'][];
    };
    /** UsersModel */
    UsersModel: {
      _embedded?: definitions['UsersEmbeddedModel'];
      _links?: definitions['Links'];
    };
  }

  export interface external {}
}
