export const wsPermissions = {
  ROLE_MASTER: 'SUPPORT',

  /*Permission Config*/
  ROLE_CONFIG_CHANGE: 'CONFIG_CHANGE',
  ROLE_CONFIG_CONSULT: 'CONFIG_CONSULT',

  /*Permission for Vouchers*/
  ROLE_VOUCHERS_CHANGE: 'VOUCHERS_CHANGE',
  ROLE_VOUCHERS_DELETE: 'VOUCHERS_DELETE',
  ROLE_VOUCHERS_CREATE: 'VOUCHERS_CREATE',
  ROLE_VOUCHERS_CONSULT: 'VOUCHERS_CONSULT',

  /*Permission for Courtesy*/
  ROLE_COURTESY_CHANGE: 'COURTESY_CHANGE',
  ROLE_COURTESY_DELETE: 'COURTESY_DELETE',
  ROLE_COURTESY_CREATE: 'COURTESY_CREATE',
  ROLE_COURTESY_CONSULT: 'COURTESY_CONSULT',
  ROLE_COURTESY_EXCHANGE: 'COURTESY_EXCHANGE',
  ROLE_COURTESY_ACTIVE_OR_INACTIVE: 'COURTESY_ACTIVE_OR_INACTIVE',

  /*Permission for Fleets*/
  ROLE_FLEETS_CHANGE: 'FLEETS_CHANGE',
  ROLE_FLEETS_DELETE: 'FLEETS_DELETE',
  ROLE_FLEETS_CREATE: 'FLEETS_CREATE',
  ROLE_FLEETS_CONSULT: 'FLEETS_CONSULT',

  /*Permission for Pool Parameters*/
  ROLE_POOL_PARAMETERS_CHANGE: 'POOL_PARAMETERS_CHANGE',
  ROLE_POOL_PARAMETERS_DELETE: 'POOL_PARAMETERS_DELETE',
  ROLE_POOL_PARAMETERS_CREATE: 'POOL_PARAMETERS_CREATE',
  ROLE_POOL_PARAMETERS_CONSULT: 'POOL_PARAMETERS_CONSULT',

  /*Permission for Chlorine Parameters*/
  ROLE_CHLORINE_PARAMETERS_CHANGE: 'CHLORINE_PARAMETERS_CHANGE',
  ROLE_CHLORINE_PARAMETERS_DELETE: 'CHLORINE_PARAMETERS_DELETE',
  ROLE_CHLORINE_PARAMETERS_CREATE: 'CHLORINE_PARAMETERS_CREATE',
  ROLE_CHLORINE_PARAMETERS_CONSULT: 'CHLORINE_PARAMETERS_CONSULT',

  /*Permission for Equipment*/
  ROLE_EQUIPMENT_CHANGE: 'EQUIPMENT_CHANGE',
  ROLE_EQUIPMENT_DELETE: 'EQUIPMENT_DELETE',
  ROLE_EQUIPMENT_CREATE: 'EQUIPMENT_CREATE',
  ROLE_EQUIPMENT_CONSULT: 'EQUIPMENT_CONSULT',

  /*Permission for Cancellation Reason*/
  ROLE_CANCELLATION_REASON_CHANGE: 'CANCELLATION_REASON_CHANGE',
  ROLE_CANCELLATION_REASON_DELETE: 'CANCELLATION_REASON_DELETE',
  ROLE_CANCELLATION_REASON_CREATE: 'CANCELLATION_REASON_CREATE',
  ROLE_CANCELLATION_REASON_CONSULT: 'CANCELLATION_REASON_CONSULT',

  /*Permission for Maintenance Carried Out*/
  ROLE_MAINTENANCE_CARRIED_OUT_CHANGE: 'MAINTENANCE_CARRIED_OUT_CHANGE',
  ROLE_MAINTENANCE_CARRIED_OUT_DELETE: 'MAINTENANCE_CARRIED_OUT_DELETE',
  ROLE_MAINTENANCE_CARRIED_OUT_CREATE: 'MAINTENANCE_CARRIED_OUT_CREATE',
  ROLE_MAINTENANCE_CARRIED_OUT_CONSULT: 'MAINTENANCE_CARRIED_OUT_CONSULT',

  /*Permission for Maintenance Schedule*/
  ROLE_MAINTENANCE_SCHEDULE_CHANGE: 'MAINTENANCE_SCHEDULE_CHANGE',
  ROLE_MAINTENANCE_SCHEDULE_DELETE: 'MAINTENANCE_SCHEDULE_DELETE',
  ROLE_MAINTENANCE_SCHEDULE_CREATE: 'MAINTENANCE_SCHEDULE_CREATE',
  ROLE_MAINTENANCE_SCHEDULE_CONSULT: 'MAINTENANCE_SCHEDULE_CONSULT',

  /*Permission for Location*/
  ROLE_LOCATION_CHANGE: 'LOCATION_CHANGE',
  ROLE_LOCATION_DELETE: 'LOCATION_DELETE',
  ROLE_LOCATION_CREATE: 'LOCATION_CREATE',
  ROLE_LOCATION_CONSULT: 'LOCATION_CONSULT',

  /*Permission for Location*/
  ROLE_HISTORIC_CHANGE: 'HISTORIC_CHANGE',
  ROLE_HISTORIC_DELETE: 'HISTORIC_DELETE',
  ROLE_HISTORIC_CREATE: 'HISTORIC_CREATE',
  ROLE_HISTORIC_CONSULT: 'HISTORIC_CONSULT',

  /*Permission for Products*/
  ROLE_PRODUCTS_CHANGE: 'PRODUCTS_CHANGE',
  ROLE_PRODUCTS_DELETE: 'PRODUCTS_DELETE',
  ROLE_PRODUCTS_CREATE: 'PRODUCTS_CREATE',
  ROLE_PRODUCTS_CONSULT: 'PRODUCTS_CONSULT',

  /*Permission for Agents*/
  ROLE_AGENTS_CHANGE: 'AGENTS_CHANGE',
  ROLE_AGENTS_DELETE: 'AGENTS_DELETE',
  ROLE_AGENTS_CREATE: 'AGENTS_CREATE',
  ROLE_AGENTS_CONSULT: 'AGENTS_CONSULT',
  ROLE_AGENTS_IS_MANAGER: 'AGENTS_IS_MANAGER',
  ROLE_AGENTS_IS_ATTENDANT: 'AGENTS_IS_ATTENDANT',

  ROLE_CLIENTS_CREATE: 'CLIENTS_CREATE',
  ROLE_CLIENTS_CONSULT: 'CLIENTS_CONSULT',
  ROLE_CLIENTS_ACTIVE_OR_INACTIVE: 'CLIENTS_ACTIVE_OR_INACTIVE',

  ROLE_PROVIDERS_CREATE: 'PROVIDERS_CREATE',
  ROLE_PROVIDERS_CONSULT: 'PROVIDERS_CONSULT',
  ROLE_PROVIDERS_ACTIVE_OR_INACTIVE: 'PROVIDERS_ACTIVE_OR_INACTIVE',

  ROLE_EMPLOYEES_CREATE: 'EMPLOYEES_CREATE',
  ROLE_EMPLOYEES_CONSULT: 'EMPLOYEES_CONSULT',
  ROLE_EMPLOYEES_ACTIVE_OR_INACTIVE: 'EMPLOYEES_ACTIVE_OR_INACTIVE',

  ROLE_PROMOTERS_CREATE: 'PROMOTERS_CREATE',
  ROLE_PROMOTERS_CONSULT: 'PROMOTERS_CONSULT',
  ROLE_PROMOTERS_ACTIVE_OR_INACTIVE: 'PROMOTERS_ACTIVE_OR_INACTIVE',

  ROLE_TOUR_GUIDE_CREATE: 'TOUR_GUIDE_CREATE',
  ROLE_TOUR_GUIDE_CONSULT: 'TOUR_GUIDE_CONSULT',
  ROLE_TOUR_GUIDE_ACTIVE_OR_INACTIVE: 'TOUR_GUIDE_ACTIVE_OR_INACTIVE',

  /* DASHBOARD */
  ROLE_VIEW_DASHBOARD_VOUCHER: 'VIEW_DASHBOARD_VOUCHER',
  ROLE_VIEW_DASHBOARD_EQUIPMENT: 'VIEW_DASHBOARD_EQUIPMENT',

  /*Permission for Users*/
  ROLE_USERS_CHANGE: 'USERS_CHANGE',
  ROLE_USERS_CREATE: 'USERS_CREATE',
  ROLE_USERS_DELETE: 'USERS_DELETE',
  ROLE_USERS_CONSULT: 'USERS_CONSULT',
  ROLE_USERS_CHANGE_PASSWORD: 'USERS_CHANGE_PASSWORD',
  ROLE_USERS_ACTIVE_OR_INACTIVE: 'USERS_ACTIVE_OR_INACTIVE',

  /*Permission for Groups*/
  ROLE_GROUPS_CHANGE: 'GROUPS_CHANGE',
  ROLE_GROUPS_CREATE: 'GROUPS_CREATE',
  ROLE_GROUPS_DELETE: 'GROUPS_DELETE',
  ROLE_GROUPS_CONSULT: 'GROUPS_CONSULT',

  /*Permission for Group User */
  ROLE_GROUP_MANAGEMENT_USER: 'GROUP_MANAGEMENT_USER',

  /*Permission for Group Permission */
  ROLE_GROUP_MANAGEMENT_PERMISSION: 'GROUP_MANAGEMENT_PERMISSION',
};
